using System.Collections.Generic;
using System.Data;
using System.Linq;

namespace ConnectKsmcDAL.Report
{
    public class R30014DAL : CommonDAL
    {
        public dynamic GetReportPatInfo(string sitecode, string patNo, string lang)
        {
            var query = $@"SELECT T_PAT_NO, T_PAT_NAME,PAT_NAME_EN,PAT_NAME_AR, MAX(T_EPISODE_NO) T_EPISODE_NO, T_GENDER, MONTHS, YEARS,T_BIRTH_DATE,ICUDAY, T_NATIONALITY, T_WARD_NO, T_WARD_DESC, T_BED_DESC, T_ROOM_NO, T_ADMIT_DATE,T_ADMIT_TIME,T_ADMIT_DOC_CODE,Doc_Name,SPC_NAME,T_PROTOCOL_NO,T_MERITAL_STATUS,T_GENDER_CODE FROM ( SELECT T03001.T_PAT_NO, PAT_NAME(T03001.T_PAT_NO, '{lang}') T_PAT_NAME,LTRIM(LTRIM(RTRIM( NVL(T03001.T_FIRST_LANG1_NAME, ''), ' '), ' ') ||' ', ' ') || LTRIM(LTRIM(RTRIM( NVL(T03001.T_FATHER_LANG1_NAME, ''), ' '), ' ') ||' ', ' ') || LTRIM(RTRIM( NVL(T03001.T_FAMILY_LANG1_NAME, ''), ' '), ' ')PAT_NAME_AR,LTRIM(LTRIM(RTRIM( NVL(T03001.T_FIRST_LANG2_NAME, ''), ' '), ' ') ||' ', ' ') || LTRIM(LTRIM(RTRIM( NVL(T03001.T_FATHER_LANG2_NAME, ''), ' '), ' ') ||' ', ' ') || LTRIM(RTRIM( NVL(T03001.T_FAMILY_LANG2_NAME, ''), ' '), ' ')PAT_NAME_EN, T_EPISODE_NO,PAT_GENDER('{patNo}', {lang}) T_GENDER,T_GENDER T_GENDER_CODE, PAT_YEAR('{patNo}') YEARS,PAT_MONTH('{patNo}') MONTHS,TO_CHAR(T03001.T_BIRTH_DATE,'dd/mm/yyyy')T_BIRTH_DATE, TRUNC(SYSDATE) - TO_DATE(T_ADMIT_DATE) ICUDAY,PAT_NATIONALITY('{patNo}', {lang}) T_NATIONALITY,T_WARD_NO, T28046.T_LANG{lang}_NAME T_WARD_DESC, T_BED_DESC,T_ROOM_NO, TO_CHAR(T_ADMIT_DATE, 'dd/MM/yyyy') T_ADMIT_DATE, T_ADMIT_TIME,T_ADMIT_DOC_CODE,T28005.T_PROTOCOL_NO, T02007.T_LANG{lang}_NAME T_MERITAL_STATUS,(select T_NAME_GIVEN||' '||T_NAME_FAMILY from t02029 where t_emp_no = T_ADMIT_DOC_CODE) Doc_Name,(SELECT T02040.T_LANG{lang}_NAME FROM T02040,T02039 WHERE T02039.T_DOC_CODE = T_ADMIT_DOC_CODE and T02039.T_SPCLTY_CODE = T02040.T_SPCLTY_CODE) SPC_NAME FROM T02003, T02006, T03001, T28005, T28010, T28046,T02007 WHERE T_GENDER = T_SEX_CODE(+) AND TO_NUMBER(T02003.T_NTNLTY_CODE) = TO_NUMBER(T03001.T_NTNLTY_CODE) AND T_LOC_CODE = T_WARD_NO AND T03001.T_PAT_NO = T28005.T_PAT_NO AND T28005.T_PAT_NO = T28010.T_PAT_NO AND T28005.T_SITE_CODE = T28010.T_SITE_CODE AND T28010.T_SITE_CODE='{sitecode}' AND  T03001.T_MRTL_STATUS=T02007.T_MRTL_STATUS_CODE(+) AND T_DISCHARGE_DATE IS NULL and T03001.T_PAT_NO = '{patNo}') GROUP BY T_PAT_NO, T_PAT_NAME,PAT_NAME_EN,PAT_NAME_AR, T_GENDER, MONTHS, YEARS,T_BIRTH_DATE,ICUDAY, T_NATIONALITY, T_WARD_NO, T_WARD_DESC, T_BED_DESC,T_ROOM_NO, T_ADMIT_DATE, T_ADMIT_TIME,T_ADMIT_DOC_CODE,Doc_Name,SPC_NAME,T_PROTOCOL_NO,T_MERITAL_STATUS,T_GENDER_CODE";
            return ReportQuery(query);
        }

        public DataTable GetReportMedicineListBySlipNo(string lang, string site, string patSeq)
        {
            var query = $@"SELECT V30112.T_MEDICINE_NAME,T30014.*,  T03001.T_FIRST_LANG{lang}_NAME || ' ' || T03001.T_FATHER_LANG{lang}_NAME || ' ' || T03001.T_FAMILY_LANG{lang}_NAME PAT_NAME,  T30014.T_PAT_MEDICINE_SEQ, T30009.T_LANG{lang}_NAME T_FREQUENCY_NAME,T30010.T_LANG{lang}_NAME T_DOSE_DURATION_NAME, {(lang == "1" ? "T30036.T_UM_SHORT_DESC_ARB" : "T30036.T_UM_SHORT_DSCRPTN")} T_UM_NAME,TO_CHAR(T30014.T_ENTRY_DATE,'DD/MM/YYYY') ENTEREDDATE,  TO_CHAR(T30014.T_UPD_DATE,'DD/MM/YYYY') UPDATEDDATE, (SELECT T_USER_NAME FROM T01009 WHERE T_EMP_CODE = T30014.T_ENTRY_USER) ENTEREDBY,(SELECT T_USER_NAME FROM T01009 WHERE T_EMP_CODE = T30014.T_UPD_USER )UPDATEDBY FROM T30014,T03001,T30009, T30010, V30112,T30036 WHERE T30014.T_PAT_MEDICINE_SEQ='{patSeq}' AND T30014.T_PAT_NO = T03001.T_PAT_NO AND T30014.T_FREQUENCY = T30009.T_FREQUENCY_CODE(+) AND T30014.T_DOSE_DURATION = T30010.T_DOSE_DURATION_CODE(+) AND T30036.T_UM = T30014.T_UM(+) AND T30014.T_ITEM_CODE = V30112.T_ITEM_CODE";
            return ReportQuery(query);
        }

        public DataTable GetData(string lang, string datefrom, string dateto)
        {
            var query = $@"SELECT DISTINCT T30014.T_PAT_MEDICINE_SEQ SLIP_NO, 
                        T03001.T_PAT_NO, PAT_NAME(T03001.T_PAT_NO, '2') T_PAT_NAME,
                        LTRIM(LTRIM(RTRIM( NVL(T03001.T_FIRST_LANG2_NAME, ''), ' '), ' ') ||' ', ' ') || 
                        LTRIM(LTRIM(RTRIM( NVL(T03001.T_FATHER_LANG2_NAME, ''), ' '), ' ') ||' ', ' ') || 
                        LTRIM(RTRIM( NVL(T03001.T_FAMILY_LANG2_NAME, ''), ' '), ' ') PAT_NAME_AR,
                        LTRIM(LTRIM(RTRIM( NVL(T03001.T_FIRST_LANG2_NAME, ''), ' '), ' ') ||' ', ' ') ||
                        LTRIM(LTRIM(RTRIM( NVL(T03001.T_FATHER_LANG2_NAME, ''), ' '), ' ') ||' ', ' ') || 
                        LTRIM(RTRIM( NVL(T03001.T_FAMILY_LANG2_NAME, ''), ' '), ' ') PAT_NAME_EN
                        ,PAT_YEAR(T03001.T_PAT_NO) YEARS
                        ,PAT_MONTH(T03001.T_PAT_NO) MONTHS
                        ,PAT_GENDER(T03001.T_PAT_NO, 2)  T_GENDER
                        ,To_Char(T30014.T_ENTRY_DATE,'dd/MM/yyyy') T_ENTRY_DATE
                        ,(SELECT T_NAME_GIVEN||' '||T_NAME_FAMILY FROM T02029 WHERE T_EMP_NO = T_ORGN_DOC) DOC_NAME
                        ,(SELECT T02040.T_LANG2_NAME FROM T02040,T02039 WHERE T02039.T_DOC_CODE = T_ORGN_DOC AND T02039.T_SPCLTY_CODE = T02040.T_SPCLTY_CODE) SPC_NAME 
                        FROM T03001, T30023 T30014
                        WHERE T30014.T_PAT_NO = T03001.T_PAT_NO
                        AND T30014.T_ENTRY_DATE BETWEEN TO_DATE('{datefrom}','dd/MM/yyyy') AND TO_DATE('{dateto}','dd/MM/yyyy')";
            return ReportQuery(query);
        }
    }
}
