using System.Data;

namespace ConnectKsmcDAL.Report
{
    public class R30190DAL : CommonDAL
    {
        public DataTable GetHeaderData(string siteCode)
        {
            return ReportQuery($@"SELECT T_SITE_CODE , T_COUNTRY_LANG1_NAME , T_COUNTRY_LANG2_NAME , T_MIN_LANG1_NAME , T_MIN_LANG2_NAME , T_SITE_LANG1_NAME , T_SITE_LANG2_NAME , T_LOGO_ID , T_LOGO_NAME , T_LOGO , T_LCENCE_NO FROM t01028 WHERE T_SITE_CODE IN(SELECT T_SITE_CODE FROM t01001)");
        }
        public DataTable GetReport(string fromDate, string toDate, string stock)
        {
            return ReportQuery($@" SELECT T_STK_LOC_CODE, V30166.T_LANG2_NAME T_STK_NAME, T_REQUEST_GCODE, T04.T_LANG2_NAME T_GEN_NAME , DRUG ,T_MOH_ITEM_CODE , COUNT(T_PAT_MEDICINE_SEQ) PATIENT , SUM(NVL(ISSUED_QUANTITY,0)) ISSUED_QUANTITY ,SUM(NVL(ORDER_QUANTITY,0)) ORDER_QUANTITY FROM V30166 JOIN T30004 T04 ON V30166.T_REQUEST_GCODE =T04.T_GEN_CODE WHERE TO_DATE(ISSUE_DATE,'dd/MM/yyyy') BETWEEN TO_DATE( '{fromDate}','dd/MM/yyyy') and TO_DATE( '{toDate}','dd/MM/yyyy') AND T_STK_LOC_CODE = NVL('{stock}',T_STK_LOC_CODE) GROUP BY T_STK_LOC_CODE,V30166. T_LANG2_NAME ,V30166.T_REQUEST_GCODE,DRUG,T_MOH_ITEM_CODE,T04.T_LANG2_NAME ORDER BY V30166.T_REQUEST_GCODE,DRUG");
        }
    }
}
