using System.Data;

namespace ConnectKsmcDAL.Report
{
    public class R30180DAL : CommonDAL
    {
        public DataTable GetHeaderData(string siteCode)
        {
            return ReportQuery($@"SELECT T_SITE_CODE , T_COUNTRY_LANG1_NAME , T_COUNTRY_LANG2_NAME , T_MIN_LANG1_NAME , T_MIN_LANG2_NAME , T_SITE_LANG1_NAME , T_SITE_LANG2_NAME , T_LOGO_ID , T_LOGO_NAME , T_LOGO , T_LCENCE_NO FROM t01028 WHERE T_SITE_CODE IN(SELECT T_SITE_CODE FROM t01001)");
        }
        public DataTable GetMasterData(string patNo)
        {
            return ReportQuery($@"SELECT T_SATURDAY, T_SUNDAY, T_MONDAY, T_TUESDAY, T_WEDNESDAY, T_THURSDAY, T_FRIDAY, (CASE WHEN T_SATURDAY IS NOT NULL THEN 'SAT' WHEN T_SUNDAY IS NOT NULL THEN 'SUN' WHEN T_MONDAY IS NOT NULL THEN 'MON' WHEN T_TUESDAY IS NOT NULL THEN 'TUE' WHEN T_WEDNESDAY IS NOT NULL THEN 'WED' WHEN T_THURSDAY IS NOT NULL THEN 'THU' WHEN T_FRIDAY IS NOT NULL THEN 'FRI' ELSE ' ' END )T_DAYS, (CASE WHEN T_SATURDAY IS NOT NULL OR T_SUNDAY IS NOT NULL OR T_MONDAY IS NOT NULL OR T_TUESDAY IS NOT NULL OR T_WEDNESDAY IS NOT NULL OR T_THURSDAY IS NOT NULL OR T_FRIDAY IS NOT NULL THEN (NVL(T_REMARKS,NULL)||' '||NVL('SAT',NULL)||NVL('SUN',NULL)|| NVL('MON',NULL)||NVL('TUE',NULL)||NVL('WED',NULL)||NVL('THU',NULL)||NVL('FRI',NULL)) ELSE '' END )T_REMARKS_DAYS, T_REMARKS, T_ITEM_CODE, T_RECEIPT_CODE, T_REQUEST_STRENGTH STRENGTH, T_DOSE_UNIT, T_DOSE_TIME_DAILY, (SELECT T_LANG2_NAME FROM T30009 WHERE T30009.T_FREQUENCY_CODE=T_DOSE_TIME_DAILY)T_DOSE_TIME_DAILY_DES, T_DOSE_DURATION, (SELECT T_LANG2_NAME FROM T30010 WHERE T30010.T_DOSE_DURATION_CODE= T_DOSE_DURATION) DOSE_DURATION, T_QTY, T_ISSUE_DATE, T_ISSUE_UM, T_ISSUE_UM, (SELECT T_UM_SHORT_DSCRPTN FROM T30036 WHERE T_UM = T_ISSUE_UM ) T_UM, (T_DOSE_UNIT ||' '|| (SELECT T_UM_SHORT_DSCRPTN FROM T30036 WHERE T_UM = T_ISSUE_UM) )T_CP_DOSE, T30023.T_ENTRY_DATE, T30023.T_DIAGNOSIS, T30023.T_UPD_USER, T01009.T_USER_NAME, T_ORGN_DOC, T_OPD_REQ_ITEM, T30023.T_STK_LOC_CODE, (SELECT T30018.T_LANG2_NAME FROM T30018 WHERE T_STK_LOC_CODE= T30023.T_STK_LOC_CODE)T_STK_LOC_NAME, T_MORNING_DOSE_UNIT, T_NOON_DOSE_UNIT, T_NIGHT_DOSE_UNIT FROM T30023 JOIN T01009 ON T30023.T_UPD_USER= T01009.T_EMP_CODE WHERE T_PAT_NO ='{patNo}' AND T_PAT_MEDICINE_SEQ = (SELECT MAX (T_PAT_MEDICINE_SEQ) FROM T30023 WHERE T_PAT_NO = '{patNo}' ) AND T_DRUG_INACTIVE_FLAG IS NULL");
        }
        public DataTable GetPatInfoData(string patNo)
        {
            return ReportQuery($@"select t_pat_no, LTRIM(LTRIM(RTRIM( NVL(T_FIRST_LANG2_NAME, ' '), ' '), ' ')||' ', ' ') || LTRIM(LTRIM(RTRIM( NVL(T_FATHER_LANG2_NAME, ' '), ' '), ' ')||' ', ' ') || LTRIM(LTRIM(RTRIM( NVL(T_GFATHER_LANG2_NAME, ' '), ' '), ' ')||' ', ' ') || LTRIM(RTRIM( NVL(T_FAMILY_LANG2_NAME, ' '), ' '), ' ') T_PAT_NAME_ENG, LTRIM(LTRIM(RTRIM( NVL(T_FIRST_LANG1_NAME, ' '), ' '), ' ')||' ', ' ') || LTRIM(LTRIM(RTRIM( NVL(T_FATHER_LANG1_NAME, ' '), ' '), ' ')||' ', ' ') || LTRIM(LTRIM(RTRIM( NVL(T_GFATHER_LANG1_NAME, ' '), ' '), ' ')||' ', ' ') || LTRIM(RTRIM( NVL(T_FAMILY_LANG1_NAME, ' '), ' '), ' ') T_PAT_NAME_ARB, T_X_RMC_CHRTNO, T_X_HOSP1_PAT_NO, T_X_HOSP2_PAT_NO, T_X_HOSP3_PAT_NO, T_X_HOSP4_PAT_NO, T_X_HOSP5_PAT_NO, T_X_HOSP6_PAT_NO, T_X_HOSP7_PAT_NO, t_payor_y, (CASE WHEN t_payor_y='1' or t_payor_y='3' THEN 'YES' ELSE 'NO' END )t_payor_des, T_GENDER, (select T_LANG2_NAME from T02006 where T_SEX_CODE=T03001.T_GENDER)T_GENDER_NAME, TO_NUMBER(TRUNC(MONTHS_BETWEEN(SYSDATE, t_BIRTH_DATE)/12,0)) ||'.'|| TO_NUMBER(TRUNC(MOD(MONTHS_BETWEEN(sysdate, t_birth_date),12),0)) Year, t_ntnlty_code, (select T_LANG2_NAME from T02003 where T02003.t_ntnlty_code =T03001.t_ntnlty_code )t_ntnlty_name from T03001 WHERE t_PAT_NO='{patNo}'");
        }
        public DataTable GetDocInfoData(string patNo, string seqNo)
        {
            return ReportQuery($@"SELECT DISTINCT T_EMP_NO HDM_DOC_CODE, rtrim(T_name_given,' ') ||' ' ||rtrim(T_NAME_FATHER,' ') ||rtrim(T_NAME_GFATHER,' ') ||' ' ||rtrim(T_name_family,' ') doc_name, T02039.T_SPCLTY_CODE HDM_SPCLTY_CODE, '(' ||DECODE(T_EMP_BADGE_NO,NULL, T_emp_phm_code, T_EMP_BADGE_NO ||'-' ||NVL(T_emp_phm_code,'N/A') ) ||')' HDM_DOC_QUALIF, (SELECT T_LANG2_NAME FROM T02041 WHERE T_DESIGN_CODE = T02039.T_DESIGNATION ) HDM_POST, (SELECT T_LANG2_NAME FROM T02040 WHERE T_spclty_code = T02039.T_SPCLTY_CODE ) HDM_CONS_SPECIALITY, (select distinct t_diagnosis from T30023 where t_diagnosis is not null and t_pat_medicine_seq='{seqNo}')t_diagnosis, (SELECT MAX(t_EPISODE_NO) FROM T30014 WHERE t_PAT_NO='{patNo}')t_EPISODE_NO FROM T02029, T02039 WHERE T02039.T_DOC_CODE = T02029.T_EMP_NO AND T02029.T_EMP_NO = (SELECT MAX(t_orgn_doc) FROM t30023 WHERE t_pat_no='{patNo}' and T_PAT_MEDICINE_SEQ='{seqNo}' AND T_DRUG_INACTIVE_FLAG IS NULL )");
        }
        public DataTable GetClinicInfoData(string patNo)
        {
            return ReportQuery($@"SELECT T_CLINIC_CODE, (SELECT DISTINCT T_CLINIC_NAME_LANG2 FROM T07001 WHERE T07001.T_CLINIC_CODE = T07003.T_CLINIC_CODE) CLINIC_NAME, T_APPT_DATE, TO_CHAR(T_APPT_DATE,'DAY') DAY, T_APPT_TIME, T_PAT_NO, T_APPT_NO FROM T07003 WHERE t_pat_no= '{patNo}' AND T_APPT_NO = (SELECT MAX(T_APPT_NO) FROM T07003 WHERE t_pat_no= '{patNo}')");
        }
    }
}
